# Generated by Django 4.0.2 on 2022-02-02 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.CharField(editable=False, max_length=70, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.CharField(editable=False, max_length=70, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpful', models.IntegerField()),
                ('reviewText', models.TextField()),
                ('overall', models.FloatField()),
                ('summary', models.CharField(max_length=70)),
                ('unixReviewTime', models.IntegerField(editable=False)),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olvy_app.product')),
                ('reviewerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olvy_app.user')),
            ],
        ),
    ]
