# Generated by Django 4.0.2 on 2022-02-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olvy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.JSONField(default={1: 0, 2: 0, 3: 0, 4: 0, 5: 0}),
        ),
    ]
